In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

In [4]:
cars = pd.read_csv("car.csv")
cars

,ID,Price,Levy,Manufacturer,Model,Prod. year,Category,Leather interior,Fuel type,Engine volume,Mileage,Cylinders,Gear box type,Drive wheels,Doors,Wheel,Color,Airbags
0,45654403,13328,1399,LEXUS,RX 450,2010,Jeep,Yes,Hybrid,3.5,186005 km,6.0,Automatic,4x4,04-May,Left wheel,Silver,12
1,44731507,16621,1018,CHEVROLET,Equinox,2011,Jeep,No,Petrol,3,192000 km,6.0,Tiptronic,4x4,04-May,Left wheel,Black,8
2,45774419,8467,-,HONDA,FIT,2006,Hatchback,No,Petrol,1.3,200000 km,4.0,Variator,Front,04-May,Right-hand drive,Black,2
3,45769185,3607,862,FORD,Escape,2011,Jeep,Yes,Hybrid,2.5,168966 km,4.0,Automatic,4x4,04-May,Left wheel,White,0
4,45809263,11726,446,HONDA,FIT,2014,Hatchback,Yes,Petrol,1.3,91901 km,4.0,Automatic,Front,04-May,Left wheel,Silver,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19232,45798355,8467,-,MERCEDES-BENZ,CLK 200,1999,Coupe,Yes,CNG,2.0 Turbo,300000 km,4.0,Manual,Rear,02-Mar,Left wheel,Silver,5
19233,45778856,15681,831,HYUNDAI,Sonata,2011,Sedan,Yes,Petrol,2.4,161600 km,4.0,Tiptronic,Front,04-May,Left wheel,Red,8
19234,45804997,26108,836,HYUNDAI,Tucson,2010,Jeep,Yes,Diesel,2,116365 km,4.0,Automatic,Front,04-May,Left wheel,Grey,4
19235,45793526,5331,1288,CHEVROLET,Captiva,2007,Jeep,Yes,Diesel,2,51258 km,4.0,Automatic,Front,04-May,Left wheel,Black,4
19236,45813273,470,753,HYUNDAI,Sonata,2012,Sedan,Yes,Hybrid,2.4,186923 km,4.0,Automatic,Front,04-May,Left wheel,White,12

In [12]:
cars.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 19237 entries, 0 to 19236
Data columns (total 13 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Price             19237 non-null  int64
 1   Levy              19237 non-null  object
 2   Manufacturer      19237 non-null  object
 3   Prod. year        19237 non-null  int64
 4   Category          19237 non-null  object
 5   Leather interior  19237 non-null  object
 6   Fuel type         19237 non-null  object
 7   Engine volume     19237 non-null  object
 8   Mileage           19237 non-null  object
 9   Cylinders         19237 non-null  float64
 10  Gear box type     19237 non-null  object
 11  Color             19237 non-null  object
 12  Airbags           19237 non-null  int64
dtypes: float64(1), int64(3), object(9)
memory usage: 1.9+ MB

In [8]:
cars['Engine volume'].value_counts()

2            3916
2.5          2277
1.8          1760
1.6          1462
1.5          1321
             ...
6.8             1
6.7             1
3.1             1
0.8 Turbo       1
1.1 Turbo       1
Name: Engine volume, Length: 107, dtype: int64

In [10]:
cars.drop(['ID', 'Drive wheels', 'Doors', 'Wheel', 'Model'], axis = 1, inplace = True)

In [11]:
cars['Mileage'] = cars['Mileage'].str.replace("km", "")
cars['Engine volume'] = cars['Engine volume'].str.replace("Turbo", "")

In [13]:
cars

,Price,Levy,Manufacturer,Prod. year,Category,Leather interior,Fuel type,Engine volume,Mileage,Cylinders,Gear box type,Color,Airbags
0,13328,1399,LEXUS,2010,Jeep,Yes,Hybrid,3.5,186005,6.0,Automatic,Silver,12
1,16621,1018,CHEVROLET,2011,Jeep,No,Petrol,3,192000,6.0,Tiptronic,Black,8
2,8467,-,HONDA,2006,Hatchback,No,Petrol,1.3,200000,4.0,Variator,Black,2
3,3607,862,FORD,2011,Jeep,Yes,Hybrid,2.5,168966,4.0,Automatic,White,0
4,11726,446,HONDA,2014,Hatchback,Yes,Petrol,1.3,91901,4.0,Automatic,Silver,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...
19232,8467,-,MERCEDES-BENZ,1999,Coupe,Yes,CNG,2.0,300000,4.0,Manual,Silver,5
19233,15681,831,HYUNDAI,2011,Sedan,Yes,Petrol,2.4,161600,4.0,Tiptronic,Red,8
19234,26108,836,HYUNDAI,2010,Jeep,Yes,Diesel,2,116365,4.0,Automatic,Grey,4
19235,5331,1288,CHEVROLET,2007,Jeep,Yes,Diesel,2,51258,4.0,Automatic,Black,4
19236,470,753,HYUNDAI,2012,Sedan,Yes,Hybrid,2.4,186923,4.0,Automatic,White,12

In [20]:
cars.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 19237 entries, 0 to 19236
Data columns (total 13 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Price             19237 non-null  int64
 1   Levy              19237 non-null  object
 2   Manufacturer      19237 non-null  object
 3   Prod. year        19237 non-null  int64
 4   Category          19237 non-null  object
 5   Leather interior  19237 non-null  object
 6   Fuel type         19237 non-null  object
 7   Engine volume     19237 non-null  object
 8   Mileage           19237 non-null  int64
 9   Cylinders         19237 non-null  int64
 10  Gear box type     19237 non-null  object
 11  Color             19237 non-null  object
 12  Airbags           19237 non-null  int64
dtypes: int64(5), object(8)
memory usage: 1.9+ MB

In [17]:
cars['Mileage'] = cars['Mileage'].astype(str).astype(int)

In [19]:
cars['Cylinders'] = cars['Cylinders'].astype(int)